name: Build Native Desktop Matrix

on:
  workflow_call:
    inputs:
      operating-system:
        description: 'Operating system for the build'
        required: true
        type: string
      arch:
        description: 'Array of architectures'
        required: false
        type: string
        default: ''
      upperShortName:
        description: 'Short name of the target'
        required: true
        type: string
      lowerShortName:
        description: 'Lower name of the target'
        required: true
        type: string

jobs:
  build-native-desktop:
    runs-on: ${{ inputs.operating-system }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build ${{ inputs.upperShortName }}${{ inputs.arch }}
        run: ./gradlew compileKotlin${{ inputs.upperShortName }}${{ inputs.arch }}

#      - name: Link ${{ inputs.upperShortName }}${{ inputs.arch }}
#        run: ./gradlew link${{ inputs.upperShortName }}${{ inputs.arch }} && ./gradlew linkReleaseShared${{ inputs.upperShortName }}${{ inputs.arch }}
#
#      - name: Generate ${{ inputs.upperShortName }}${{ inputs.arch }} binaries
#        run: ./gradlew ${{ inputs.lowerShortName }}${{ inputs.arch }}Binaries