name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List Targets
        id: list-targets
        run: targets=$(./gradlew listTargets | grep 'Target:' | cut -d' ' -f2) && echo "targets=$targets"

  build-android:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Android
        run: ./gradlew assembleDebug && ./gradlew assembleRelease

  build-ios:
    runs-on: macos-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build iOS Frameworks
        run: ./gradlew linkReleaseFrameworkIosArm64 linkReleaseFrameworkIosSimulatorArm64 linkReleaseFrameworkIosX64

  build-macos:
    runs-on: macos-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build MacOS x64
        run: ./gradlew compileKotlinMacosX64

      - name: Link MacOS x64
        run: ./gradlew linkMacosX64 && ./gradlew linkDebugSharedMacosX64 && ./gradlew linkReleaseSharedMacosX64

      - name: Generate MacOS x64 binaries
        run: ./gradlew macosX64Binaries

      - name: Build MacOS Arm64
        run: ./gradlew compileKotlinMacosArm64

      - name: Link MacOS Arm64
        run: ./gradlew linkMacosArm64 && ./gradlew linkReleaseSharedMacosArm64

      - name: Generate MacOS Arm64 binaries
        run: ./gradlew macosArm64Binaries

  build-linux:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Linux x64
        run: ./gradlew compileKotlinLinuxX64

      - name: Link Linux x64
        run: ./gradlew linkLinuxX64 && ./gradlew linkReleaseSharedLinuxX64

      - name: Generate Linux x64 binaries
        run: ./gradlew linuxX64Binaries

      - name: Build Linux Arm64
        run: ./gradlew compileKotlinLinuxArm64

      - name: Link Linux Arm64
        run: ./gradlew linkLinuxArm64 && ./gradlew linkReleaseSharedLinuxArm64

      - name: Generate Linux Arm64 binaries
        run: ./gradlew linuxArm64Binaries

  build-windows:
    runs-on: windows-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Windows
        run: ./gradlew compileKotlinWindows

      - name: Link Windows
        run: ./gradlew linkWindows && ./gradlew linkReleaseSharedWindows

      - name: Generate Windows binaries
        run: ./gradlew windowsBinaries

  build-js:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JS
        run: ./gradlew jsBrowserProductionWebpack

  build-jvm:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JVM
        run: ./gradlew jvmJar

  test-android:
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test Android
        run: ./gradlew testDebugUnitTest

  test-ios:
    runs-on: macos-latest
    needs: build-ios
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test iOS
        run: ./gradlew iosArm64TestBinaries

  test-macos:
    runs-on: macos-latest
    needs: build-macos
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test MacOS X64
        run: ./gradlew macosX64TestBinaries && ./gradlew macosX64TestKlibrary

      - name: Test MacOS Arm64
        run: ./gradlew macosArm64TestBinaries && ./gradlew macosArm64TestKlibrary

  test-linux:
    runs-on: ubuntu-latest
    needs: build-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test Linux X64
        run: ./gradlew linuxX64TestBinaries && ./gradlew linuxX64TestKlibrary

      - name: Test Linux Arm64
        run: ./gradlew linuxArm64TestBinaries && ./gradlew linuxArm64TestKlibrary

  test-windows:
    runs-on: windows-latest
    needs: build-windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test Windows
        run: ./gradlew windowsTestBinaries && ./gradlew windowsTestKlibrary

  test-js:
    runs-on: ubuntu-latest
    needs: build-js
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Chromium
        run: sudo apt-get update & sudo apt-get install -y chromium-browser

      - name: Test JS
        run: ./gradlew jsTestClasses

      - name: Test Node Package
        run: ./gradlew jsTestPackageJson

      - name: Browser test
        run: ./gradlew jsBrowserRun

  test-jvm:
    runs-on: ubuntu-latest
    needs: build-jvm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test JVM
        run: ./gradlew jvmTestClasses