name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List Targets
        id: list-targets
        run: targets=$(./gradlew listTargets | grep 'Target:' | cut -d' ' -f2) && echo "targets=$targets"

  build-android:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Android
        run: ./gradlew assembleDebug && ./gradlew assembleRelease

  build-ios:
    runs-on: macos-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build iOS Frameworks
        run: ./gradlew linkReleaseFrameworkIosArm64 linkReleaseFrameworkIosSimulatorArm64 linkReleaseFrameworkIosX64

  build-macos:
    needs: prepare
    uses: sanlean/Minesweeper/.github/workflows/build-native-desktop.yml@main
    strategy:
      matrix:
        arch: [X64, Arm64]
    with:
      operating-system: macos-latest
      arch: ${{ matrix.arch }}
      upperShortName: Macos
      lowerShortName: macos

  build-linux:
    needs: prepare
    uses: sanlean/Minesweeper/.github/workflows/build-native-desktop.yml@main
    strategy:
      matrix:
        arch: [X64, Arm64]
    with:
      operating-system: ubuntu-latest
      arch: ${{ matrix.arch }}
      upperShortName: Linux
      lowerShortName: linux

  build-windows:
    needs: prepare
    uses: sanlean/Minesweeper/.github/workflows/build-native-desktop.yml@main
    with:
      operating-system: windows-latest
      upperShortName: Windows
      lowerShortName: windows

  build-js:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JS
        run: ./gradlew jsBrowserProductionWebpack

  build-jvm:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JVM
        run: ./gradlew jvmJar

  test-android:
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test Android
        run: ./gradlew testDebugUnitTest

  test-ios:
    runs-on: macos-latest
    needs: build-ios
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test iOS
        run: ./gradlew iosArm64TestBinaries

  test-macos:
    needs: build-macos
    uses: sanlean/Minesweeper/.github/workflows/build-native-desktop.yml@main
    strategy:
      matrix:
        arch: [X64, Arm64]
    with:
      operating-system: macos-latest
      arch: ${{ matrix.arch }}
      upperShortName: Macos
      lowerShortName: macos

  test-linux:
    needs: build-linux
    uses: sanlean/Minesweeper/.github/workflows/test-native-desktop.yml@main
    strategy:
      matrix:
        arch: [X64, Arm64]
    with:
      operating-system: ubuntu-latest
      arch: ${{ matrix.arch }}
      upperShortName: Linux
      lowerShortName: linux

  test-windows:
    needs: build-windows
    uses: sanlean/Minesweeper/.github/workflows/build-native-desktop.yml@main
    with:
      operating-system: windows-latest
      arch: ${{ matrix.arch }}
      upperShortName: Windows
      lowerShortName: windows

  test-js:
    runs-on: ubuntu-latest
    needs: build-js
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Chromium
        run: sudo apt-get update & sudo apt-get install -y chromium-browser

      - name: Test JS Classes
        run: ./gradlew jsTestClasses

      - name: Test JS
        run: ./gradlew jsTest

      - name: Test Node Package
        run: ./gradlew jsTestPackageJson

  test-jvm:
    runs-on: ubuntu-latest
    needs: build-jvm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test JVM
        run: ./gradlew jvmTestClasses