name: Build Native Desktop Matrix

on:
  workflow_call:
    inputs:
      operating-system:
        description: 'Operating system for the build'
        required: true
        type: string
      arch:
        description: 'Architecture'
        required: false
        type: string
        default: ''
      upperShortName:
        description: 'Short name of the target'
        required: true
        type: string
      lowerShortName:
        description: 'Short name of the target'
        required: true
        type: string

jobs:
  build-native-desktop:
    runs-on: ${{ inputs.operating-system }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test ${{ inputs.upperShortName }}${{ inputs.arch }} Binaries
        run: ./gradlew ${{ inputs.lowerShortName }}${{ inputs.arch }}TestBinaries

      - name: Test ${{ inputs.upperShortName }}${{ inputs.arch }} Klibrary
        run: ./gradlew ${{ inputs.lowerShortName }}${{ inputs.arch }}TestKlibrary